# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2f2261af34d07dd474f819f7756ebf58288057bac6bd4c3ef561166f7000c045139d8fbc79af40ff55226182d85973ffd098fabd20a625643a6bac90d9a21eb

test:
  secret_key_base: 54700b4727bcc411868ee13d9cd17d8af42fa6c4f36d748b760abb5781800a336b13bd2d9dc8ea0a4dd2c9d96cea4f0ea7c437f8badcd9ba6fdfd6ca35dc1ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
